#!/usr/bin/env bash

export DEBUG=*sp-*

yarn pre:deploy
DEFAULT_ENVIRONMENT=live sls deploy -s staging -r us-east-1 --force
DEFAULT_ENVIRONMENT=sandbox sls deploy -s staging -r us-west-2 --force
yarn post:deploy
